name: release-build
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Push Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write # needed for signing the images with GitHub OIDC Token **not production ready**

    # keda-tools is built from github.com/test-tools/tools/Dockerfile
    container: ghcr.io/kedacore/keda-tools:1.20.5
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Register workspace path
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - id: go-paths
        run: |
          echo ::set-output name=mod_cache::$(go env GOMODCACHE)
          echo ::set-output name=build_cache::$(go env GOCACHE)

      - name: Go modules cache
        uses: actions/cache@v3.3.1
        with:
          path: ${{ steps.go-paths.outputs.mod_cache }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: Go build cache
        uses: actions/cache@v3.3.1
        with:
          path: ${{ steps.go-paths.outputs.build_cache }}
          key: ${{ runner.os }}-go-build-cache-${{ hashFiles('**/go.sum') }}

      - name: Go modules sync
        run: go mod tidy -compat=1.20

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Release Deployment YAML file
        run: make release
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}

        # Get release information to determine id of the current release
      - name: Get Release
        id: get-release-info
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload deployment YAML file to GitHub release
      - name: Upload Deployment YAML file
        id: upload-deployment-yaml
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/kedacore/keda/releases/${{ steps.get-release-info.outputs.id }}/assets?name=keda-${{ steps.get_version.outputs.VERSION }}.yaml
          asset_path: keda-${{ steps.get_version.outputs.VERSION }}.yaml
          asset_name: keda-${{ steps.get_version.outputs.VERSION }}.yaml
          asset_content_type: application/x-yaml

      # Upload core deployment YAML file to GitHub release (TO BE DELETED FOR v2.12)
      - name: Upload Deployment YAML file
        id: upload-core-deployment-yaml
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/kedacore/keda/releases/${{ steps.get-release-info.outputs.id }}/assets?name=keda-${{ steps.get_version.outputs.VERSION }}-core.yaml
          asset_path: keda-${{ steps.get_version.outputs.VERSION }}-core.yaml
          asset_name: keda-${{ steps.get_version.outputs.VERSION }}-core.yaml
          asset_content_type: application/x-yaml

      # Upload CRD deployment YAML file to GitHub release
      - name: Upload Deployment YAML file
        id: upload-crd-deployment-yaml
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/kedacore/keda/releases/${{ steps.get-release-info.outputs.id }}/assets?name=keda-${{ steps.get_version.outputs.VERSION }}-crds.yaml
          asset_path: keda-${{ steps.get_version.outputs.VERSION }}-crds.yaml
          asset_name: keda-${{ steps.get_version.outputs.VERSION }}-crds.yaml
          asset_content_type: application/x-yamlv
